export const Data = [
    {
        id: "1",
        img_src: "/images/1.jpg",
        name: "Armless Chair CHR4002 Plastic Chair (Bright Red) by GN Furniture (6PC Combo)",
        desc: "this is the item",
        category: "category1",
        Weight: "1000",
        mrp: "2000",
        discount: "20",
        qty: 0,
    },
    {
        id: "2",
        img_src: "https://m.media-amazon.com/images/I/61coJ3JMC7L._AC_UL480_FMwebp_QL65_.jpg",
        name: "Armless Chair CHR4001",
        desc: "this is the item",
        category: "category1",
        Weight: "1000",
        mrp: "2500",
        discount: "20",
        qty: 0,
    },
    {
        id: "3",
        img_src: "https://m.media-amazon.com/images/I/81fQmDN1nvL._AC_UL480_FMwebp_QL65_.jpg",
        name: "Amazon Brand - Stone & Beam Waynes Fabric Accent/Lounge Chair (Blue)",
        desc: "this is the item",
        category: "category2",
        Weight: "1000",
        mrp: "5500",
        discount: "20",
        qty: 0,
        mrpn: "MRP"
    },
    {
        id: "4",
        img_src: "https://m.media-amazon.com/images/I/61gl9-ez6UL._AC_UL480_FMwebp_QL65_.jpg",
        name: "Armless Chair CHR4002 Plastic Chair (Pear Wood) by GN Furniture (4PC Combo)",
        desc: "this is the item",
        category: "category2",
        Weight: "1000",
        mrp: "1500",
        discount: "20",
        qty: 0
    },
    {
        id: "5",
        img_src: "https://m.media-amazon.com/images/I/51jejNqBhyL._AC_UL480_FMwebp_QL65_.jpg",
        name: "Armless Chair CHR4001",
        desc: "this is the item",
        category: "category3",
        Weight: "1000",
        mrp: "3000",
        discount: "20",
        qty: 0
    },
    {
        id: "6",
        img_src: "https://m.media-amazon.com/images/I/41MtaHN08RL._AC_UL480_FMwebp_QL65_.jpg",
        name: "Black Modern Cane Chair",
        desc: "this is the item",
        category: "category3",
        Weight: "1000",
        mrp: "4000",
        discount: "20",
        qty: 0
    },
    {
        id: "7",
        img_src: "https://m.media-amazon.com/images/I/61iBE4Nhu0L._AC_UL480_FMwebp_QL65_.jpg",
        name: "AVRO FURNITURE, 2581 Plastic Chairs, Set of 2 Pcs, Plastic Modern Ergonomic Chair Without Cushion, 200 kilograms (Orange), 2 Pieces",
        desc: "this is the item",
        category: "category4",
        Weight: "1000",
        mrp: "5000",
        discount: "20",
        qty: 0
    },
    {
        id: "8",
        img_src: "https://m.media-amazon.com/images/I/61p683nGweL._AC_UL480_FMwebp_QL65_.jpg",
        name: "Armless Chair",
        desc: "this is the item",
        category: "category1",
        Weight: "1000",
        mrp: "2000",
        discount: "20",
        qty: 0
    },
    {
        id: "9",
        img_src: "https://m.media-amazon.com/images/I/61gl9-ez6UL._AC_UL480_FMwebp_QL65_.jpg",
        name: "(Pear Wood) by GN Furniture (4PC Combo)",
        desc: "this is the item",
        category: "category2",
        Weight: "1000",
        mrp: "1500",
        discount: "20",
        qty: 0
    },
    {
        id: "10",
        img_src: "https://m.media-amazon.com/images/I/51jejNqBhyL._AC_UL480_FMwebp_QL65_.jpg",
        name: "Armless Chair",
        desc: "this is the item",
        category: "category3",
        Weight: "1000",
        mrp: "3000",
        discount: "20",
        qty: 0
    },
    {
        id: "11",
        img_src: "https://m.media-amazon.com/images/I/41MtaHN08RL._AC_UL480_FMwebp_QL65_.jpg",
        name: "Cane Chair",
        desc: "this is the item",
        category: "category3",
        Weight: "1000",
        mrp: "4000",
        discount: "20",
        qty: 0
    },
    {
        id: "12",
        img_src: "https://m.media-amazon.com/images/I/61iBE4Nhu0L._AC_UL480_FMwebp_QL65_.jpg",
        name: "AVRO FURNITURE,2 Pieces",
        desc: "this is the item",
        category: "category4",
        Weight: "1000",
        mrp: "5000",
        discount: "20",
        qty: 0
    },
    
]